### PR TITLE
revise Alert isZero to check Title and Action

### PR DESCRIPTION
**Pull request by nathany**
as @willfaught mentioned here: https://github.com/timehop/apns/issues/28#issuecomment-76021621

### CODE REVIEW

**Comment by tylrtrmbl** [comment]
This is relevant today. I'd recommend merging! @bdotdub

**Comment by tylrtrmbl** [comment]
Technically two failures. I'd check that out, looks like legitimately failed tests.

**Comment by nathany** [comment]
Those are the issue in #12.

**Comment by tylrtrmbl** [comment]
Awesome, thanks for clarifying.

**Comment by bdotdub** [comment]
lgtm! going to merge

**Pull request merged**
